
namespace WebAPIWithPS
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AzureCommandResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzureCommandResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAPIWithPS.AzureCommandResource", typeof(AzureCommandResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to $ServerList = $SessionHost.Split(&quot;,&quot;)
        ///Add-RDSessionHost -CollectionName $CollectionName -SessionHost $ServerList  -ConnectionBroker $ConnectionBroker.
        /// </summary>
        internal static string getLocalProcesses
        {
            get
            {
                return ResourceManager.GetString("getLocalProcesses", resourceCulture);
            }
        }


        internal static string getAzureVMDetails
        {
            get
            {
                return ResourceManager.GetString("getAzureVMDetails", resourceCulture);
            }
        }

        internal static string Azure_ServerState_PS
        {
            get
            {
                return ResourceManager.GetString("Azure_ServerState_PS", resourceCulture);
            }
        }

        internal static string Azure_SQLServerState_PS
        {
            get
            {
                return ResourceManager.GetString("Azure_SQLServerState_PS", resourceCulture);
            }
        }
    }
}
